### PR TITLE
Adjust keword args formatting

### PR DESCRIPTION
**Pull request by anthmatic**
Adjusts the keyword args formatting to remain on one line if possible and break up if the tag does not fit on one line.

### CODE REVIEW

**Comment by anthmatic** [comment]
> Hmm, I read the comments where this is stemming from -- I'm wondering if there is a possibility of breaking to multiple lines based on the number of parameters?

This is _sort of_ whats happening currently except that it's line length that tells prettier when to start wrapping items, which is the typical way that prettier will handle formatting. In most cases it would be difficult to break based on the number of items because AST nodes can be nested deeply. But, in the case of KeywordArgs I think we may be able to wrap based on number pretty easily, it would just be inconsistent with most other wrapping logic. This is an example of something that would be on one line today and what it could look like if we break when there are two or more keyword args (and skipping other nodes like the name)

image

Personally, I find both to be pretty readable so happy to head in whichever direction folks feel strongly about.

> Additionally, from the old tests, I can see that the closing %} hubL bracket was sitting on the same line as the last param - which pushing that to a separate line would be preferred.

It's been quite a battle to make that work reliably but I can take another look in a separate PR

**Comment by TanyaScales** [comment]
> This is an example of something that would be on one line today and what it could look like if we break when there are two or more keyword args (and skipping other nodes like the name)
> 
> image
> 
> Personally, I find both to be pretty readable so happy to head in whichever direction folks feel strongly about.

Is this something that we can add a configuration option for? I feel like breaking to new lines should be the default and if a developer is truly unsatisfied with that -- we can allow them to opt out of it.

(Not sure what the current situation is with rule configs and whatnot in prettier -- I know they lock theirs down pretty tightly but not sure if we have any leverage on our side to offer a couple things.

---

> > Additionally, from the old tests, I can see that the closing %} hubL bracket was sitting on the same line as the last param - which pushing that to a separate line would be preferred.
> 
> It's been quite a battle to make that work reliably but I can take another look in a separate PR

It might not be worth it -- because this would only be applicable in the case where the tag wraps -- one liners should keep the closing `%}` on the same line. So that adds a bit of complexity to the situation as well.

**Comment by anthmatic** [comment]
> (Not sure what the current situation is with rule configs and whatnot in prettier -- I know they lock theirs down pretty tightly but not sure if we have any leverage on our side to offer a couple things.

The Prettier maintainers' stance is that they generally don't add options but we can definitely do what works for us. In general, I'd like to avoid options but I'm definitely open to adding them as needed and especially to protect backwards compatibility.

> breaking to new lines should be the default

By this, do you mean we ALWAYS break keyword arguments onto new lines, even if there is only 1?
```
{% follow_me "name"
  title="Follow Us" %}
```

>It might not be worth it -- because this would only be applicable in the case where the tag wraps -- one liners should keep the closing %} on the same line. So that adds a bit of complexity to the situation as well.

I think my preference for this would be to keep as-is and introduce an option in the future if there are requests for that format and we find a way to implement it. Does that sound ok for now?

**Comment by TanyaScales** [comment]
> > (Not sure what the current situation is with rule configs and whatnot in prettier -- I know they lock theirs down pretty tightly but not sure if we have any leverage on our side to offer a couple things.
> 
> The Prettier maintainers' stance is that they generally don't add options but we can definitely do what works for us. In general, I'd like to avoid options but I'm definitely open to adding them as needed and especially to protect backwards compatibility.

Yeah, I think we need to determine if we are being opinionated like Prettier and saying "this is the way it goes" -- which I'm okay with doing if we feel comfortable as a group saying its because this is what we find most legible/best practice.

> 
> > breaking to new lines should be the default
> 
> By this, do you mean we ALWAYS break keyword arguments onto new lines, even if there is only 1?

Ah, no, I meant it should always be the default when there is more than one argument

> 
> ```
> {% follow_me "name"
>   title="Follow Us" %}
> ```
> 
> > It might not be worth it -- because this would only be applicable in the case where the tag wraps -- one liners should keep the closing %} on the same line. So that adds a bit of complexity to the situation as well.
> 
> I think my preference for this would be to keep as-is and introduce an option in the future if there are requests for that format and we find a way to implement it. Does that sound ok for now?

Yeah, I think that is fair -- especially if its a bit of a pain right now

**Comment by anthmatic** [comment]
> Yeah, I think we need to determine if we are being opinionated like Prettier and saying "this is the way it goes" -- which I'm okay with doing if we feel comfortable as a group saying its because this is what we find most legible/best practice.

Agreed!

> Ah, no, I meant it should always be the default when there is more than one argument

Gotcha, will update this to break if kw args > 1

> Yeah, I think that is fair -- especially if its a bit of a pain right now

👍

**Pull request merged**
